### ISSUE TITLE
Current version of project is old and not as per given screenshots in Gitlab

### ISSUE THREAD

**Issue by thenewsbyte** [Jit-Bdr-Rana/Hacker4me#1]
Current version of project is old and not as per given screenshots in Gitlab. Can you please upload or provide the final version of the project? I also need this.

**Comment by Jit-Bdr-Rana** [comment]
it's in gitlab bro see there

**Comment by thenewsbyte** [comment]
So if I clone that repo and run project in my system will it run fine?
because I've already tried many times but I am getting partial forms, pages
of login, registration.

**Comment by Jit-Bdr-Rana** [comment]
yes it run ...i think you have issue in installation .

**Comment by thenewsbyte** [comment]
Okay. Thanks for letting me know. I will try again.

**Comment by Jit-Bdr-Rana** [comment]
ok best up luck bro ..
